# Generated by Django 2.2.5 on 2020-05-26 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_goodschannelgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodschannel',
            old_name='group_id',
            new_name='group',
        ),
    ]
